-- MySQL Script generated by MySQL Workbench
-- Qua 06 Jul 2016 01:05:42 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

DROP DATABASE IF EXISTS `tcc`;
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

DROP USER IF EXISTS 'tcc'@'localhost';
CREATE USER 'tcc'@'localhost' identified by '@senha_tcc';
GRANT ALL PRIVILEGES ON tcc.* TO 'tcc'@'localhost';

-- -----------------------------------------------------
-- Table `tcc`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`admins` (
  `id` INT NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`cidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`, `estado_id`),
  INDEX `fk_cidades_estados1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidades_estados1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `tcc`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`clientes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `telefone1` VARCHAR(45) NULL,
  `telefone2` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`gerentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`gerentes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`restaurantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`restaurantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL,
  `descricao` TEXT NULL,
  `foto` VARCHAR(255) NULL,
  `horario_abre` VARCHAR(5) NULL,
  `horario_fecha` VARCHAR(5) NULL,
  `tempo_mercado` VARCHAR(45) NULL,
  `valor_min` VARCHAR(45) NOT NULL,
  `telefone1` VARCHAR(45) NULL,
  `telefone2` VARCHAR(45) NULL,
  `gerente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `gerente_id`),
  INDEX `fk_restaurante_gerente1_idx` (`gerente_id` ASC),
  CONSTRAINT `fk_restaurante_gerente1`
    FOREIGN KEY (`gerente_id`)
    REFERENCES `tcc`.`gerentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`atendentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`atendentes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `restaurante_id` INT NOT NULL,
  PRIMARY KEY (`id`, `restaurante_id`),
  INDEX `fk_atendente_restaurante1_idx` (`restaurante_id` ASC),
  CONSTRAINT `fk_atendente_restaurante1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `tcc`.`restaurantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`produtos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `tipo` INT NULL,
  `descricao` VARCHAR(150) NULL,
  `preco` DOUBLE NOT NULL,
  `foto` VARCHAR(45) NULL,
  `qtd_max_complemento` INT NULL,
  `restaurante_id` INT NOT NULL,
  PRIMARY KEY (`id`, `restaurante_id`),
  INDEX `fk_produto_restaurante_idx` (`restaurante_id` ASC),
  CONSTRAINT `fk_produto_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `tcc`.`restaurantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`sugestaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`sugestaos` (
  `id` INT NOT NULL,
  `nome_restaurante` VARCHAR(45) NOT NULL,
  `mensagem` VARCHAR(255) NULL,
  `tel_restaurante` VARCHAR(45) NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cliente_id`),
  INDEX `fk_sugestao_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_sugestao_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tcc`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pedidos` (
  `id` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  `status` INT NOT NULL,
  `data` DATE NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cliente_id`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tcc`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`enderecos` (
  `id` INT NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `complemento` VARCHAR(60) NULL,
  `cep` VARCHAR(15) NOT NULL,
  `tipo` INT NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cidade_id`),
  INDEX `fk_endereços_cidades1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_endereços_cidades1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `tcc`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`classificacaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`classificacaos` (
  `id` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  `comentario` VARCHAR(120) NULL,
  `restaurante_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `restaurante_id`, `cliente_id`),
  INDEX `fk_classificacao_restaurante1_idx` (`restaurante_id` ASC),
  INDEX `fk_classificacao_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_classificacao_restaurante1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `tcc`.`restaurantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classificacao_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tcc`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`complementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`complementos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` INT NOT NULL,
  `descricao` VARCHAR(80) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `produto_id`),
  INDEX `fk_complemento_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_complemento_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `tcc`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`tipo_culinarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`culinarias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `restaurante_id` INT NOT NULL,
  PRIMARY KEY (`id`, `restaurante_id`),
  INDEX `fk_tipoCulinarias_restaurantes1_idx` (`restaurante_id` ASC),
  CONSTRAINT `fk_tipoCulinarias_restaurantes1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `tcc`.`restaurantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`forma_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pagamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(80) NOT NULL,
  `restaurante_id` INT NOT NULL,
  PRIMARY KEY (`id`, `restaurante_id`),
  INDEX `fk_formasPagamentos_restaurantes1_idx` (`restaurante_id` ASC),
  CONSTRAINT `fk_formasPagamentos_restaurantes1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `tcc`.`restaurantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`pedidos_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pedido_produtos` (
  `pedido_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `qtd` INT NOT NULL,
  PRIMARY KEY (`pedido_id`, `produto_id`),
  INDEX `fk_pedidos_has_produtos_produtos1_idx` (`produto_id` ASC),
  INDEX `fk_pedidos_has_produtos_pedidos1_idx` (`pedido_id` ASC),
  CONSTRAINT `fk_pedidos_has_produtos_pedidos1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `tcc`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_produtos_produtos1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `tcc`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`clientes_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`cliente_enderecos` (
  `cliente_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`cliente_id`, `endereco_id`),
  INDEX `fk_clientes_has_enderecos_enderecos1_idx` (`endereco_id` ASC),
  INDEX `fk_clientes_has_enderecos_clientes1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_clientes_has_enderecos_clientes1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tcc`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_enderecos_enderecos1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `tcc`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`enderecos_restaurantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`restaurante_enderecos` (
  `endereco_id` INT NOT NULL,
  `restaurante_id` INT NOT NULL,
  PRIMARY KEY (`endereco_id`, `restaurante_id`),
  INDEX `fk_enderecos_has_restaurantes_restaurantes1_idx` (`restaurante_id` ASC),
  INDEX `fk_enderecos_has_restaurantes_enderecos1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_enderecos_has_restaurantes_enderecos1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `tcc`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enderecos_has_restaurantes_restaurantes1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `tcc`.`restaurantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tcc`.`promocaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`promocaos` (
  `restaurante_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `data_ini` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `desconto` INT NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`restaurante_id`, `produto_id`),
  INDEX `fk_promocaos_produtos1_idx` (`produto_id` ASC),
  INDEX `fk_promocaos_restaurantes1_idx` (`restaurante_id` ASC),
  CONSTRAINT `fk_promocaos_restaurantes1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `tcc`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promocaos_produtos1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `tcc`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
